server:
  address: 127.0.0.1
  port: 8080
  servlet:
    context-path: /ksm
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver   
    url: jdbc:mysql://127.0.0.1:3306/ksm?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: lingAN03.[]